- dashboard: dp_pruebas_9
  title: DP_Pruebas_9_modelado
  layout: newspaper
  preferred_viewer: dashboards-next
  description: ''
  preferred_slug: yIXdvaml0Q9YY7Hue2iWFu
  elements:
  - title: Dummy1
    name: Dummy1
    model: demo_looker_genia
    explore: demo_tac
    type: looker_waterfall
    fields: [demo_tac.total_ano, demo_tac.Utilidad_neta, demo_tac.Total_ingresos]
    filters: {}
    sorts: [demo_tac.total_ano desc 0]
    limit: 500
    column_limit: 50
    up_color: false
    down_color: false
    total_color: false
    show_value_labels: false
    show_x_axis_ticks: true
    show_x_axis_label: true
    x_axis_scale: auto
    show_y_axis_labels: true
    show_y_axis_ticks: true
    y_axis_gridlines: true
    color_application:
      collection_id: jazz
      palette_id: jazz-diverging-0
      options:
        steps: 5
    circleThickness: 0.05
    circleFillGap: 0.7
    waveHeight: 0.5
    waveCount: 5
    waveRiseTime: 1300
    waveAnimateTime: 2501
    waveRise: true
    waveColor: "#FADBD8"
    waveOffset: 0.5
    textVertPosition: 0.61
    textSize: 0.63
    displayPercent: false
    hidden_pivots: {}
    x_axis_gridlines: false
    show_view_names: false
    y_axis_tick_density: default
    y_axis_tick_density_custom: 5
    y_axis_scale_mode: linear
    x_axis_reversed: false
    y_axis_reversed: false
    plot_size_by_field: false
    trellis: ''
    stacking: ''
    limit_displayed_rows: false
    legend_position: center
    point_style: none
    label_density: 25
    y_axis_combined: true
    ordering: none
    show_null_labels: false
    show_totals_labels: false
    show_silhouette: false
    totals_color: "#808080"
    defaults_version: 1
    hidden_fields: []
    hidden_points_if_no: []
    series_labels: {}
    listen:
      Moneda: demo_tac.moneda
    row: 4
    col: 0
    width: 18
    height: 6
  - title: Utilidad Neta
    name: Utilidad Neta
    model: demo_looker_genia
    explore: demo_tac
    type: marketplace_viz_radial_gauge::radial_gauge-marketplace
    fields: [demo_tac.Utilidad_neta]
    limit: 500
    column_limit: 50
    hidden_fields: []
    hidden_points_if_no: []
    series_labels: {}
    show_view_names: true
    arm_length: 0
    arm_weight: 0
    spinner_length: 0
    spinner_weight: 21
    target_length: 14
    target_gap: 15
    target_weight: 50
    value_label_type: both
    value_label_font: -1
    value_label_padding: 60
    fill_color: "#FAE5D3"
    background_color: "#FAE5D3"
    spinner_color: "#E8DAEF"
    range_color: "#000000"
    gauge_fill_type: progress-gradient
    angle: 90
    cutout: 65
    range_x: -2
    range_y: -1.6
    target_label_padding: 1.58
    custom_color_enabled: true
    show_single_value_title: true
    show_comparison: false
    comparison_type: value
    comparison_reverse_colors: false
    show_comparison_label: true
    enable_conditional_formatting: false
    conditional_formatting_include_totals: false
    conditional_formatting_include_nulls: false
    defaults_version: 0
    hidden_pivots: {}
    listen:
      Moneda: demo_tac.moneda
    row: 0
    col: 0
    width: 8
    height: 4
  - title: Valor Moneda
    name: Valor Moneda
    model: demo_looker_genia
    explore: demo_tac
    type: marketplace_viz_radial_gauge::radial_gauge-marketplace
    fields: [demo_tac.Valor_moneda]
    limit: 500
    column_limit: 50
    hidden_fields: []
    hidden_points_if_no: []
    series_labels: {}
    show_view_names: true
    arm_length: 0
    arm_weight: 0
    spinner_length: 0
    spinner_weight: 21
    target_length: 14
    target_gap: 15
    target_weight: 50
    value_label_type: both
    value_label_font: -1
    value_label_padding: 60
    fill_color: "#FAE5D3"
    background_color: "#FAE5D3"
    spinner_color: "#E8DAEF"
    range_color: "#000000"
    gauge_fill_type: progress-gradient
    angle: 90
    cutout: 65
    range_x: -2
    range_y: -1.6
    target_label_padding: 1.58
    custom_color_enabled: true
    show_single_value_title: true
    show_comparison: false
    comparison_type: value
    comparison_reverse_colors: false
    show_comparison_label: true
    enable_conditional_formatting: false
    conditional_formatting_include_totals: false
    conditional_formatting_include_nulls: false
    defaults_version: 0
    hidden_pivots: {}
    listen:
      Moneda: demo_tac.moneda
    row: 16
    col: 0
    width: 13
    height: 5
  - title: Antes impuestos
    name: Antes impuestos
    model: demo_looker_genia
    explore: demo_tac
    type: marketplace_viz_radial_gauge::radial_gauge-marketplace
    fields: [demo_tac.Antes_impuestos]
    limit: 500
    column_limit: 50
    hidden_fields: []
    hidden_points_if_no: []
    series_labels: {}
    show_view_names: true
    arm_length: 0
    arm_weight: 0
    spinner_length: 0
    spinner_weight: 21
    target_length: 14
    target_gap: 15
    target_weight: 50
    value_label_type: both
    value_label_font: -1
    value_label_padding: 60
    fill_color: "#FAE5D3"
    background_color: "#FAE5D3"
    spinner_color: "#E8DAEF"
    range_color: "#000000"
    gauge_fill_type: progress-gradient
    angle: 90
    cutout: 65
    range_x: -2
    range_y: -1.6
    target_label_padding: 1.58
    custom_color_enabled: true
    show_single_value_title: true
    show_comparison: false
    comparison_type: value
    comparison_reverse_colors: false
    show_comparison_label: true
    enable_conditional_formatting: false
    conditional_formatting_include_totals: false
    conditional_formatting_include_nulls: false
    defaults_version: 0
    hidden_pivots: {}
    listen:
      Moneda: demo_tac.moneda
    row: 0
    col: 16
    width: 8
    height: 4
  - title: Impuestos año anterior
    name: Impuestos año anterior
    model: demo_looker_genia
    explore: demo_tac
    type: marketplace_viz_radial_gauge::radial_gauge-marketplace
    fields: [demo_tac.Antes_impuestos_anio_anterior]
    limit: 500
    column_limit: 50
    hidden_fields: []
    hidden_points_if_no: []
    series_labels: {}
    show_view_names: true
    arm_length: 0
    arm_weight: 0
    spinner_length: 0
    spinner_weight: 21
    target_length: 14
    target_gap: 15
    target_weight: 50
    value_label_type: both
    value_label_font: -1
    value_label_padding: 60
    fill_color: "#FAE5D3"
    background_color: "#FAE5D3"
    spinner_color: "#E8DAEF"
    range_color: "#000000"
    gauge_fill_type: progress-gradient
    angle: 90
    cutout: 65
    range_x: -2
    range_y: -1.6
    target_label_padding: 1.58
    custom_color_enabled: true
    show_single_value_title: true
    show_comparison: false
    comparison_type: value
    comparison_reverse_colors: false
    show_comparison_label: true
    enable_conditional_formatting: false
    conditional_formatting_include_totals: false
    conditional_formatting_include_nulls: false
    defaults_version: 0
    hidden_pivots: {}
    listen:
      Moneda: demo_tac.moneda
    row: 0
    col: 8
    width: 8
    height: 4
  - title: Pais vs antes impuestos
    name: Pais vs antes impuestos
    model: demo_looker_genia
    explore: demo_tac
    type: wazeforcitieswilson::chartjs
    fields: [demo_tac.pais, demo_tac.Antes_impuestos]
    sorts: [demo_tac.Antes_impuestos desc 0]
    limit: 500
    column_limit: 50
    hidden_fields: []
    hidden_points_if_no: []
    series_labels: {}
    show_view_names: false
    hidden_pivots: {}
    x_axis_gridlines: false
    y_axis_gridlines: true
    show_y_axis_labels: true
    show_y_axis_ticks: true
    y_axis_tick_density: default
    y_axis_tick_density_custom: 5
    show_x_axis_label: true
    show_x_axis_ticks: true
    y_axis_scale_mode: linear
    x_axis_reversed: false
    y_axis_reversed: false
    plot_size_by_field: false
    trellis: ''
    stacking: ''
    limit_displayed_rows: false
    legend_position: center
    point_style: none
    show_value_labels: false
    label_density: 25
    x_axis_scale: auto
    y_axis_combined: true
    ordering: none
    show_null_labels: false
    show_totals_labels: false
    show_silhouette: false
    totals_color: "#808080"
    defaults_version: 0
    color_application: undefined
    listen:
      Moneda: demo_tac.moneda
    row: 10
    col: 15
    width: 9
    height: 6
  - title: Pais promedio año
    name: Pais promedio año
    model: demo_looker_genia
    explore: demo_tac
    type: marketplace_viz_histogram::histogram-marketplace
    fields: [demo_tac.pais, demo_tac.average_ano]
    sorts: [demo_tac.average_ano desc 0]
    limit: 500
    column_limit: 50
    hidden_fields: []
    hidden_points_if_no: []
    series_labels: {}
    show_view_names: false
    bin_type: bins
    bin_style: simple_hist
    winsorization: false
    color_col: "#e8111a"
    color_on_hover: "#96ff2d"
    x_axis_override: ''
    x_grids: true
    x_axis_title_font_size: 16
    x_axis_label_font_size: 12
    x_axis_label_angle: 6
    x_label_separation: 100
    y_axis_override: ''
    y_grids: true
    y_axis_title_font_size: 16
    y_axis_label_font_size: 12
    y_axis_label_angle: 0
    y_label_separation: 100
    x_axis_value_format: ''
    max_bins: '10'
    hidden_pivots: {}
    x_axis_gridlines: false
    y_axis_gridlines: true
    show_y_axis_labels: true
    show_y_axis_ticks: true
    y_axis_tick_density: default
    y_axis_tick_density_custom: 5
    show_x_axis_label: true
    show_x_axis_ticks: true
    y_axis_scale_mode: linear
    x_axis_reversed: false
    y_axis_reversed: false
    plot_size_by_field: false
    trellis: ''
    stacking: ''
    limit_displayed_rows: false
    legend_position: center
    point_style: none
    show_value_labels: false
    label_density: 25
    x_axis_scale: auto
    y_axis_combined: true
    ordering: none
    show_null_labels: false
    show_totals_labels: false
    show_silhouette: false
    totals_color: "#808080"
    defaults_version: 0
    color_application: undefined
    listen:
      Moneda: demo_tac.moneda
    row: 16
    col: 13
    width: 11
    height: 5
  - title: Utilidad neta vs total ano
    name: Utilidad neta vs total ano
    model: demo_looker_genia
    explore: demo_tac
    type: marketplace_viz_multiple_value::multiple_value-marketplace
    fields: [demo_tac.Utilidad_neta, demo_tac.total_ano]
    limit: 500
    column_limit: 50
    hidden_fields: []
    hidden_points_if_no: []
    series_labels: {}
    show_view_names: true
    hidden_pivots: {}
    defaults_version: 0
    listen:
      Moneda: demo_tac.moneda
    row: 4
    col: 18
    width: 6
    height: 6
  - title: Cartoon
    name: Cartoon
    model: demo_looker_genia
    explore: demo_tac
    type: marketplace_viz_cartoon::cartoon_vis
    fields: [demo_tac.ano, demo_tac.Total_ingresos]
    sorts: [demo_tac.Total_ingresos desc 0]
    limit: 500
    column_limit: 50
    hidden_fields: []
    hidden_points_if_no: []
    series_labels: {}
    show_view_names: true
    hidden_pivots: {}
    defaults_version: 0
    x_axis_gridlines: false
    y_axis_gridlines: true
    show_y_axis_labels: true
    show_y_axis_ticks: true
    y_axis_tick_density: default
    y_axis_tick_density_custom: 5
    show_x_axis_label: true
    show_x_axis_ticks: true
    y_axis_scale_mode: linear
    x_axis_reversed: false
    y_axis_reversed: false
    plot_size_by_field: false
    trellis: ''
    stacking: ''
    limit_displayed_rows: false
    legend_position: center
    point_style: none
    show_value_labels: false
    label_density: 25
    x_axis_scale: auto
    y_axis_combined: true
    show_null_points: true
    interpolation: linear
    listen:
      Moneda: demo_tac.moneda
    row: 10
    col: 0
    width: 15
    height: 6
  filters:
  - name: Moneda
    title: Moneda
    type: field_filter
    default_value: LOCAL
    allow_multiple_values: true
    required: false
    ui_config:
      type: dropdown_menu
      display: inline
    model: demo_looker_genia
    explore: demo_tac
    listens_to_filters: []
    field: demo_tac.moneda
